---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-build
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cluster-build
subjects:
- kind: ServiceAccount
  name: cluster-build
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-build
  namespace: default
type: Opaque
data:
  gitrepo: <insert_base64_encoded_git_repo_URL_here>
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-build
  namespace: default
spec:
  template:
    spec:
      initContainers:
      - name: cluster-build-apply
        image: chipzoller/k8s-addon-bootstrap:latest
        command: ["/bin/sh"]
        args: ["-c", "git clone $(GIT_REPO) manifests/ && kubectl apply -f manifests/ -R"]
        env:
        - name: GIT_REPO
          valueFrom:
            secretKeyRef:
              name: cluster-build
              key: gitrepo
      containers:
      - name: cluster-build-cleanup
        image: chipzoller/k8s-addon-bootstrap:latest
        command: ["kubectl", "delete", "secrets/cluster-build"]
      restartPolicy: Never
      serviceAccountName: cluster-build
